[lint]

select = [
    "E",  # Pycodestyle errors (replaces Flake8's rules)
    "F",  # Pyflakes errors (similar to Flake8)
    "B",  # Bugbear rules (Prospector and Flake8 compatible)
    "I",  # Import-related errors
]
ignore = [
    "E501",  # Ignore line length errors (optional)
    "I001",  # Don't require sorted imports
    "B008",  # Incompatible with FastAPI Dependency declaration
    "B039",  # Do not use mutable data structures for `ContextVar` defaults

]